name: Lint GitHub Actions Workflows

on:
  pull_request:
  push:
    branches:
      - main
      - 'release/*'

jobs:
  lint:
    name: Run Actionlint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'  # Ensure the version of Go matches the requirements of Actionlint

    - name: Install Actionlint
      run: |
        go install github.com/rhysd/actionlint/cmd/actionlint@latest

    #  - name: Run Actionlint
     #   run: |
      #    actionlint
        
    - name: Run Actionlint
      shell: pwsh
      run: |
        # Run actionlint and capture the output and exit code
        $exitCode = $LASTEXITCODE
        echo $exitCode
        echo "actionlint...."
        $actionlintOutput = & actionlint -color 2>&1  # Redirect stderr to stdout to capture all output
        
        echo "actionlint.... done"
        echo $actionlintOutput
        Write-Host $actionlintOutput
        $exitCode = $LASTEXITCODE
        echo $exitCode
        # ANSI escape codes for color
        $Red = "`e[31m"
        $Green = "`e[32m"
        $Yellow = "`e[33m"
        $NoColor = "`e[0m"
        
        # Check the exit code to handle failures
        if ($exitCode -ne 0) {
            Write-Host "$Red$actionlintOutput$NoColor"
        } elseif ($actionlintOutput -match "warning") {
            Write-Host "$Yellow$actionlintOutput$NoColor"
        } else {
            Write-Host "$Green$actionlintOutput$NoColor"
        }
        
        # Optional: return non-zero exit code if actionlint failed
        exit $exitCode


