name: Lint GitHub Actions Workflows

on:
  pull_request:
  push:
    branches:
      - main
      - 'release/*'

jobs:
  lint:
    name: Run Actionlint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'  # Ensure the version of Go matches the requirements of Actionlint

    - name: Install Actionlint
      run: |
        go install github.com/rhysd/actionlint/cmd/actionlint@latest

    - name: Run Actionlint
      run: |
        actionlint_output=$(actionlint)

        # Color codes
        RED='\033[0;31m'
        GREEN='\033[0;32m'
        YELLOW='\033[0;33m'
        NC='\033[0m' # No Color
        
        # Example of coloring the output
        if echo "$actionlint_output" | grep -q "error"; then
            echo -e "${RED}$actionlint_output${NC}"
        elif echo "$actionlint_output" | grep -q "warning"; then
            echo -e "${YELLOW}$actionlint_output${NC}"
        else
            echo -e "${GREEN}$actionlint_output${NC}"
        fi
