name: Lint GitHub Actions Workflows

on:
  pull_request:
  push:
    branches:
      - main
      - 'release/*'

jobs:
  lint:
    name: Run Actionlint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'  # Ensure the version of Go matches the requirements of Actionlint

    - name: Install Actionlint
      run: |
        go install github.com/rhysd/actionlint/cmd/actionlint@latest

    #  - name: Run Actionlint
     #   run: |
      #    actionlint
        
    - name: Run Actionlint
      shell: pwsh
      run: |
        # Run actionlint and capture the output and exit code
        $exitCode = $LASTEXITCODE
        echo $exitCode
        echo "actionlint...."
        $actionlintOutput = & actionlint -color 2>&1  # Redirect stderr to stdout to capture all output
        
        echo "actionlint.... done"
        # same as Write-Output, echo $actionlintOutput
        Write-Output $actionlintOutput
        $exitCode = $LASTEXITCODE
        
        # Check the exit code to handle failures
        if ($exitCode -ne 0) {
            Write-Host "No error in linting good work!"
        } else {
            Write-Host "Exit error"
        }
        
        # Optional: return non-zero exit code if actionlint failed
        exit $exitCode


